[features]
seeds = false
skip-lint = false
[programs.localnet]
nft_grab = "FteJ8GhF78qjo4acX7LmXi9RwzBcDnUax4FoB6xsMNA9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/chain/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
