[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
escrow = "83RUW9YEDBBs2wAq4P4uTGv5Egr6oM5693yvZpg2czFd"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/*.ts"

[features]
